export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const STATIC_CONTENT_USER = 'STATIC_CONTENT_USER';
export const STATIC_CONTENT_ADMIN = 'STATIC_CONTENT_ADMIN';
export const STATIC_CONTENT_DEFAULT = 'STATIC_CONTENT_DEFAULT';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
