export const SIGN_IN_FORM = 'SIGN_IN_FORM';
export const SIGN_UP_FORM = 'SIGN_UP_FORM';
export const RESET_PASS_FORM = 'RESET_PASS_FORM';
export const RESET_PASS_CONFIRM_FORM = 'RESET_PASS_CONFIRM_FORM';
export const PERSONAL_INFO_FORM = 'PERSONAL_INFO_FORM';
export const PROFILE_SETTINGS_FORM = 'PROFILE_SETTINGS_FORM';
